### ISSUE TITLE
HA log entries: MultipleInvalid: string value is None for dictionary value @ data['unit_of_measurement'] 

### ISSUE THREAD

**Issue by jedie** [jedie/pysmartmeter#39]
The HA log in the Web-GUI under Settings / Logs contains many entries from pysmartmeter: `string value is None for dictionary value @ data['unit_of_measurement']`

```python
Exception in async_discover when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'device_class': 'energy', 'device': {'name': 'EBZ5...
Traceback (most recent call last): 
File "/var/www/homeassistant/lib/python3.10/site-packages/homeassistant/components/mqtt/mixins.py", line 316, in async_discover config: 
    DiscoveryInfoType = discovery_schema(discovery_payload) 
File "/var/www/homeassistant/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v) 
File "/var/www/homeassistant/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path) 
File "/var/www/homeassistant/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v) 
File "/var/www/homeassistant/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data) 
File "/var/www/homeassistant/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data) 
File "/var/www/homeassistant/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data) 
File "/var/www/homeassistant/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out) 
File "/var/www/homeassistant/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: 
string value is None for dictionary value @ data['unit_of_measurement']
```

**Comment by jedie** [comment]
fixed in v0.7
